### PR TITLE
add to support `Index Signatures`

### PR DESCRIPTION
**Pull request by horiuchi**
change `additionalProperties`s value for the index signature support.

via:
Index Signature: http://www.typescriptlang.org/Handbook#interfaces-array-types
additionalProperties: http://spacetelescope.github.io/understanding-json-schema/reference/object.html#properties

### CODE REVIEW

**Comment by horiuchi** [comment]
Why test filed on Node4.2 or Node4.1?
Do you know why timeout error?
In my local environment Node4.2, timeout error didn't occurred.

**Comment by shiwano** [comment]
> Do you know why timeout error?

I have no idea, but the travis task that I just retried is finished successfully. :expressionless:

**Comment by shiwano** [comment]
It's very usefull change! :+1: :sparkles: :star:

**Comment by shiwano** [comment]
https://github.com/shiwano/typhen-json-schema/commit/6b5bca5e30c7e0eb161962362a213083736c773a

The default value of mocha timeout was a bit short. I changed the value to 10000 ms from 2000 ms.

**Comment by horiuchi** [comment]
@shiwano Thank you for changing timeout value! :star2:

**Pull request merged**
